# Generated by Django 6.0.1 on 2026-01-14 03:44

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='#1 Rated Academic Consultancy', help_text='Top badge text', max_length=100)),
                ('title', django_ckeditor_5.fields.CKEditor5Field(help_text='Main title (Bold/Color supported)')),
                ('subtitle', models.TextField(default='Stop stressing over deadlines. Connect with elite mentors for custom essays, complex thesis research, and expert data analysis.')),
                ('hero_image', models.ImageField(blank=True, help_text='Background image', null=True, upload_to='hero/')),
                ('button_1_text', models.CharField(default='Get Started', max_length=50)),
                ('button_1_url', models.CharField(default='#', max_length=200)),
                ('button_2_text', models.CharField(default='View Services', max_length=50)),
                ('button_2_url', models.CharField(default='#', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.AlterField(
            model_name='offerbanner',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Offer text (Bold supported)'),
        ),
    ]
