# Generated by Django 6.0.1 on 2026-01-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_herosection_alter_offerbanner_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='title',
            field=models.TextField(help_text='Main title (HTML supported)'),
        ),
    ]
