# Generated by Django 6.0.1 on 2026-01-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_herosection_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='button_1_url',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='button_2_url',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='title',
        ),
        migrations.AddField(
            model_name='herosection',
            name='stat_1_label',
            field=models.CharField(default='Happy Students', max_length=50),
        ),
        migrations.AddField(
            model_name='herosection',
            name='stat_1_number',
            field=models.CharField(default='10k+', max_length=20),
        ),
        migrations.AddField(
            model_name='herosection',
            name='stat_2_label',
            field=models.CharField(default='Success Rate', max_length=50),
        ),
        migrations.AddField(
            model_name='herosection',
            name='stat_2_number',
            field=models.CharField(default='98%', max_length=20),
        ),
        migrations.AddField(
            model_name='herosection',
            name='stat_3_label',
            field=models.CharField(default='PhD Experts', max_length=50),
        ),
        migrations.AddField(
            model_name='herosection',
            name='stat_3_number',
            field=models.CharField(default='500+', max_length=20),
        ),
        migrations.AddField(
            model_name='herosection',
            name='stat_4_label',
            field=models.CharField(default='Support', max_length=50),
        ),
        migrations.AddField(
            model_name='herosection',
            name='stat_4_number',
            field=models.CharField(default='24/7', max_length=20),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_highlight',
            field=models.CharField(default='Guaranteed.', help_text='Highlighted part of title (Color)', max_length=200),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_leading',
            field=models.CharField(default='Academic Excellence, ', help_text='First part of title (White)', max_length=200),
        ),
    ]
