# Generated by Django 6.0.1 on 2026-01-14 17:18

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_remove_herosection_button_1_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of the title', unique=True)),
                ('author', models.CharField(default='Admin', max_length=100)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(help_text='Blog content')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='blog_thumbnails/')),
                ('category', models.CharField(default='General', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='herosection',
            name='button_1_text',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='button_2_text',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='stat_1_label',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='stat_1_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='stat_2_label',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='stat_2_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='stat_3_label',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='stat_3_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='stat_4_label',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='stat_4_number',
            field=models.CharField(max_length=20),
        ),
    ]
