# Generated by Django 6.0.1 on 2026-01-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_blogpost_alter_herosection_button_1_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='summary',
            field=models.TextField(default='', help_text='Short summary for list view and search, and for SEO meta description'),
        ),
    ]
