# Generated by Django 6.0.1 on 2026-01-21 11:16

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_alter_blogpost_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='H1: Professional Essay Writing Service', max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('hero_image', models.ImageField(help_text='Mandatory Hero Banner', upload_to='services/hero/')),
                ('thumbnail', models.ImageField(blank=True, help_text='For list view', null=True, upload_to='services/thumbnails/')),
                ('intro_description', models.TextField(help_text='Intro (2–3 lines – definition style)')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(help_text='Main content with H2s, H3s, images, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='H1: Subject Name', max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('hero_image', models.ImageField(help_text='Mandatory Hero Banner', upload_to='subjects/hero/')),
                ('thumbnail', models.ImageField(blank=True, help_text='For list view', null=True, upload_to='subjects/thumbnails/')),
                ('intro_description', models.TextField(help_text='Intro (2–3 lines – definition style)')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(help_text='Main content with H2s, H3s, images, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
