# Generated by Django 6.0.1 on 2026-01-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_service_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='show_in_menu',
            field=models.BooleanField(default=False, help_text='Show in navigation menu (Max 5 recommended)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='show_in_menu',
            field=models.BooleanField(default=False, help_text='Show in navigation menu (Max 5 recommended)'),
        ),
    ]
