# Generated by Django 6.0.1 on 2026-01-21 11:40

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_privacypolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Terms & Conditions', max_length=200)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(help_text='Terms & Conditions Content')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Terms & Conditions',
            },
        ),
    ]
