# Generated by Django 6.0.1 on 2026-01-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_termscondition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(help_text="Student's name", max_length=100)),
                ('student_initials', models.CharField(default='AB', help_text='2-3 letter initials for avatar', max_length=5)),
                ('course_field', models.CharField(help_text='e.g., Business Management, Computer Science', max_length=100)),
                ('rating', models.IntegerField(default=5, help_text='Rating out of 5')),
                ('message', models.TextField(help_text='Testimonial message')),
                ('is_active', models.BooleanField(default=True, help_text='Show on homepage')),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
