# Generated by Django 6.0.1 on 2026-01-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTABanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Ready to Boost Your Grades?', help_text='Main heading', max_length=200)),
                ('subtitle', models.TextField(default='Join thousands of successful students who trust OAH. Get professional support today.', help_text='Subtitle text')),
                ('button_text', models.CharField(default='Book Your Expert Now', help_text='CTA button text', max_length=50)),
                ('button_link', models.CharField(default='book-now.html', help_text='Button link URL', max_length=200)),
                ('feature_1', models.CharField(default='Plagiarism-Free', help_text='First feature', max_length=100)),
                ('feature_2', models.CharField(default='On-Time Delivery', help_text='Second feature', max_length=100)),
                ('feature_3', models.CharField(default='Confidential', help_text='Third feature', max_length=100)),
                ('guarantee_title', models.CharField(default='Money Back', help_text='Guarantee badge title', max_length=100)),
                ('guarantee_subtitle', models.CharField(default='Guarantee', help_text='Guarantee badge subtitle', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Show on homepage')),
            ],
            options={
                'verbose_name': 'CTA Banner',
                'verbose_name_plural': 'CTA Banner',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='FAQ question', max_length=300)),
                ('answer', models.TextField(help_text='FAQ answer')),
                ('is_active', models.BooleanField(default=True, help_text='Show on homepage')),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
