# Generated by Django 6.0.1 on 2026-01-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_ctabanner_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_badge', models.CharField(default='Our Story', help_text='Badge text above heading', max_length=50)),
                ('story_title', models.CharField(default='Empowering Students Since 2014', max_length=200)),
                ('story_lead', models.TextField(default='We started with a simple mission: to bridge the gap between academic pressure and student success.')),
                ('story_description', models.TextField(default='Since our inception, we have helped over 50,000 students achieve their academic goals.')),
                ('story_image', models.ImageField(blank=True, help_text='Story section image', null=True, upload_to='about/')),
                ('vision_title', models.CharField(default='Our Vision', max_length=100)),
                ('vision_text', models.TextField(default="To be the world's most trusted academic support platform.")),
                ('mission_title', models.CharField(default='Our Mission', max_length=100)),
                ('mission_text', models.TextField(default='To provide high-quality, personalized academic assistance.')),
                ('company_name', models.CharField(default='Original Assignment Help (OAH)', max_length=200)),
                ('company_legal_name', models.CharField(default='Harviera IT Solutions LLP', max_length=200)),
                ('company_description', models.TextField(default='A registered Limited Liability Partnership incorporated under the laws of India.')),
                ('headquarters_location', models.CharField(default='Palwal, Haryana, India', max_length=200)),
                ('students_helped', models.CharField(default='50,000+', max_length=20)),
                ('success_rate', models.CharField(default='98%', max_length=20)),
                ('years_experience', models.CharField(default='10+', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Excellence, Integrity', max_length=100)),
                ('description', models.TextField(help_text='Short description of this value')),
                ('icon_class', models.CharField(default='bi-award', help_text='Bootstrap icon class (e.g., bi-award)', max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='e.g., 2014, Present', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
