# Generated by Django 6.0.1 on 2026-01-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_aboutpage_corevalue_milestone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Guide title', max_length=200)),
                ('description', models.TextField(help_text='Short description')),
                ('category', models.CharField(help_text='e.g., Citation, Writing, Research', max_length=100)),
                ('pdf_file', models.FileField(help_text='Upload PDF file', upload_to='guides/')),
                ('icon_class', models.CharField(default='bi-journal-richtext', help_text='Bootstrap icon class', max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SampleWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Sample work title', max_length=200)),
                ('description', models.TextField(help_text='Brief description')),
                ('category', models.CharField(help_text='e.g., Essay, Case Study, Research Paper', max_length=100)),
                ('academic_level', models.CharField(help_text='e.g., MBA, Undergraduate, PhD', max_length=50)),
                ('file', models.FileField(help_text='Upload sample file', upload_to='sample_works/')),
                ('file_type', models.CharField(default='PDF', help_text='PDF or DOCX', max_length=10)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sample Work',
                'verbose_name_plural': 'Sample Works',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tool name', max_length=200)),
                ('description', models.TextField(help_text='What this tool does')),
                ('external_link', models.URLField(help_text='External tool URL')),
                ('icon_class', models.CharField(default='bi-tools', help_text='Bootstrap icon class', max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
