# Generated by Django 6.0.1 on 2026-01-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0015_guide_samplework_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='company_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='company_legal_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='company_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='headquarters_location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='mission_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='mission_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='story_badge',
            field=models.CharField(help_text='Badge text above heading', max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='story_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='story_lead',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='story_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='students_helped',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='success_rate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='vision_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='vision_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='years_experience',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ctabanner',
            name='button_link',
            field=models.CharField(help_text='Button link URL', max_length=200),
        ),
        migrations.AlterField(
            model_name='ctabanner',
            name='button_text',
            field=models.CharField(help_text='CTA button text', max_length=50),
        ),
        migrations.AlterField(
            model_name='ctabanner',
            name='feature_1',
            field=models.CharField(help_text='First feature', max_length=100),
        ),
        migrations.AlterField(
            model_name='ctabanner',
            name='feature_2',
            field=models.CharField(help_text='Second feature', max_length=100),
        ),
        migrations.AlterField(
            model_name='ctabanner',
            name='feature_3',
            field=models.CharField(help_text='Third feature', max_length=100),
        ),
        migrations.AlterField(
            model_name='ctabanner',
            name='guarantee_subtitle',
            field=models.CharField(help_text='Guarantee badge subtitle', max_length=100),
        ),
        migrations.AlterField(
            model_name='ctabanner',
            name='guarantee_title',
            field=models.CharField(help_text='Guarantee badge title', max_length=100),
        ),
        migrations.AlterField(
            model_name='ctabanner',
            name='subtitle',
            field=models.TextField(help_text='Subtitle text'),
        ),
        migrations.AlterField(
            model_name='ctabanner',
            name='title',
            field=models.CharField(help_text='Main heading', max_length=200),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='badge_text',
            field=models.CharField(help_text='Top badge text', max_length=100),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='subtitle',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title_highlight',
            field=models.CharField(help_text='Highlighted part of title (Color)', max_length=200),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title_leading',
            field=models.CharField(help_text='First part of title (White)', max_length=200),
        ),
    ]
