# Generated by Django 6.0.1 on 2026-01-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_alter_aboutpage_company_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_description', models.TextField(help_text='Footer description text')),
                ('email', models.EmailField(help_text='Contact email', max_length=254)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('whatsapp_number', models.CharField(help_text='WhatsApp number', max_length=20)),
                ('head_office_address', models.TextField(help_text='Head Office Address')),
                ('branch_office_address', models.TextField(help_text='Branch Office Address')),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('copyright_text', models.CharField(default='© 2014 originalassignmenthelp.com - Operated by Harviera IT Solutions', max_length=255)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
