# Generated by Django 6.0.1 on 2026-01-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='hero_bg_image',
            field=models.ImageField(blank=True, help_text='Background image for the header', null=True, upload_to='about/hero/'),
        ),
    ]
