# Generated by Django 6.0.1 on 2026-01-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0018_aboutpage_hero_bg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='timeline_description',
            field=models.TextField(default='Key milestones in our story.'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='timeline_title',
            field=models.CharField(default='Our Journey', max_length=100),
        ),
    ]
