# Generated by Django 6.0.1 on 2026-01-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0019_aboutpage_timeline_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Large full-width image for the middle section', null=True, upload_to='about/featured/'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='featured_image_title',
            field=models.CharField(default='Global Impact', help_text='Title overlay for the image', max_length=200),
        ),
    ]
