# Generated by Django 6.0.1 on 2026-01-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0020_aboutpage_featured_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Get in Touch', max_length=200)),
                ('hero_subtitle', models.TextField(default='Have questions? Were here to help! Reach out to our support team anytime.')),
                ('whatsapp_title', models.CharField(default='Chat on WhatsApp', max_length=200)),
                ('whatsapp_subtitle', models.CharField(default='Available 24/7 for instant replies.', max_length=200)),
                ('whatsapp_number', models.CharField(default='919959691347', max_length=20)),
                ('whatsapp_response_time', models.CharField(default='< 2 minutes', max_length=100)),
                ('email_title', models.CharField(default='Email Support', max_length=200)),
                ('email_description', models.CharField(default='For detailed inquiries or attachments.', max_length=200)),
                ('email_address', models.EmailField(default='support@academichelp.com', max_length=254)),
                ('head_office_title', models.CharField(default='Head Office', max_length=200)),
                ('head_office_address', models.TextField(default='Old GT Rd, Gandhi Ashram Colony, Palwal, India, 121102')),
                ('branch_office_title', models.CharField(default='Branch Office', max_length=200)),
                ('branch_office_address', models.TextField(default='Near Kamineni Hospital, LB Nagar, Hyderabad, Telangana, India - 500074')),
                ('map_embed_url', models.URLField(help_text='Google Maps embed URL', max_length=1000)),
                ('map_overlay_text', models.TextField(default='We are located centrally in Palwal. Drop by for a coffee and consultation.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Page',
                'verbose_name_plural': 'Contact Page',
            },
        ),
    ]
