# Generated by Django 6.0.1 on 2026-01-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0021_contactpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='branch_map_embed_url',
            field=models.URLField(blank=True, help_text='Google Maps embed URL for Branch Office', max_length=1000),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='map_embed_url',
            field=models.URLField(help_text='Google Maps embed URL for Head Office', max_length=1000),
        ),
    ]
