# Generated by Django 6.0.1 on 2026-01-22 18:56

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0022_contactpage_branch_map_embed_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Refund & Money-Back Guarantee Policy', max_length=200)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(help_text='Refund Policy Content')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Refund Policy',
            },
        ),
    ]
