# Generated by Django 6.0.1 on 2026-01-23 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0023_refundpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='external_link',
            field=models.URLField(blank=True, help_text='Or provide a direct link (e.g. Google Drive, Website)', null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload PDF file (Optional if Link provided)', null=True, upload_to='guides/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='samplework',
            name='file',
            field=models.FileField(help_text='Upload sample file (PDF, DOCX, DOC, ZIP)', upload_to='sample_works/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc', 'zip'])]),
        ),
    ]
