# Generated by Django 6.0.3 on 2026-04-07 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0024_guide_external_link_alter_guide_pdf_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='category',
        ),
    ]
